default:
  replicaCount: 1

  image:
    repository: prom/prometheus
    pullPolicy: IfNotPresent
    tag: "v2.52.0"

  service:
    type: ClusterIP
    port: 9090

  ingress:
    enabled: true
    className: "nginx"
    annotations:
      kubernetes.io/ingress.class: nginx
    hosts:
      - host: prometheus.meuteste.com
        paths:
          - path: /
            pathType: Prefix
    tls: []

  volumeMounts:
    - name: prometheus-storage
      mountPath: /prometheus

  volumes:
    - name: prometheus-storage
      persistentVolumeClaim:
        claimName: prometheus-default-pvc

  storageClass:
    create: false
    name: local-storage

  persistence:
    enabled: true
    size: 5Gi
    storageClass: local-storage

  persistentVolume:
    create: true
    path: /mnt/data/prometheus  # Caminho no nó
    node: worker1

  kubeStateMetrics:
    enabled: true
    fullnameOverride: prometheus-kube-state-metrics
    

  nodeExporter:
    enabled: true
    fullnameOverride: prometheus-node-exporter

  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

  autoscaling:
    enabled: false
    minReplicas: 1
    maxReplicas: 3
    targetCPUUtilizationPercentage: 80

  securityContext:
    runAsUser: 0
