namespace: monitoring

prometheus:
  enabled: true
  service:
    type: ClusterIP
    port: 9090
  persistence:
    enabled: true
    size: 10Gi

grafana:
  enabled: true
  service:
    type: ClusterIP
    port: 3000
  persistence:
    enabled: true
    size: 5Gi
  adminUser: admin
  adminPassword: admin
  dashboards:
    default:
      prometheus-dashboard:
        gnetId: 11074
        revision: 1
        datasource: Prometheus

ingress:
  enabled: true
  ingressClassName: nginx  # 🔹 Define o IngressClass como nginx
  prometheus:
    host: prometheus.meusite.com
    path: /
  grafana:
    host: grafana.meusite.com
    path: /
